/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lascaux

import java.io.File

import org.jetbrains.kotlin.cli.common.CLIConfigurationKeys
import org.jetbrains.kotlin.cli.common.arguments.K2JVMCompilerArguments
import org.jetbrains.kotlin.cli.common.messages.MessageCollector
import org.jetbrains.kotlin.cli.jvm.K2JVMCompiler
import org.jetbrains.kotlin.config.Services
import org.jetbrains.kotlin.config.CompilerConfiguration

import org.bukkit.Bukkit
import org.bukkit.plugin.java.JavaPlugin

public class LascauxPlugin : JavaPlugin() {
    override fun onEnable() {
        /*logger.info("Loading stuff!")
        val dataFolderPath = getDataFolder().path
        val pl = Bukkit.getPluginManager().loadPlugin(File(dataFolderPath + "/thing.jar"))
        if (pl != null) {
            Bukkit.getPluginManager().enablePlugin(pl)
        }
        logger.info("Done!")*/
    }
}
